language: julia

julia:
  - 0.7
  - 1.0

os:
  - linux

notifications:
  email: mkolar@gmail.com

addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev
        - libgmp-dev
        - libglpk-dev

sudo: false

# script:
#   - julia -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'

after_success:
    - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
